services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  python_app:
    build: .
    container_name: python_service
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_NAME=main_db
      - DB_USER=user
      - DB_PASS=password
    command: streamlit run dashboard/app.py

volumes:
  pgdata: